### ISSUE TITLE
Cannot create requested ontology format

### ISSUE THREAD

**Issue by lewismc** [ESIPFed/cor#33] opened 2017-04-12 00:08 UTC
I tried manually uploading some RDF data and encountered the issue below. Is the following URI illegal?

**file:/usr/local/ESIPDroneClusterSoftware/example/morning1.csvAirSpeed(m/s)**

```
"org.mmisw.orr.ont.service.CannotCreateFormat: Map(uri -> http://cor.esipfed.org/ont/~lmcgibbn/morning1, version -> 20170412T000427, format -> rdf, error -> Cannot create requested ontology format: com.hp.hpl.jena.shared.InvalidPropertyURIException: file:/usr/local/ESIPDroneClusterSoftware/example/morning1.csvAirSpeed(m/s))\n\tat org.mmisw.orr.ont.service.OntService.getOntologyFile(OntService.scala:265)\n\tat org.mmisw.orr.ont.service.TripleStoreServiceAgRest.loadUriFromLocal(TripleStoreServiceAgRest.scala:109)\n\tat org.mmisw.orr.ont.app.OntController.org$mmisw$orr$ont$app$OntController$$loadOntologyInTripleStore(OntController.scala:634)\n\tat org.mmisw.orr.ont.app.OntController.org$mmisw$orr$ont$app$OntController$$createOntology(OntController.scala:399)\n\tat org.mmisw.orr.ont.app.OntController$$anonfun$7.apply(OntController.scala:123)\n\tat org.mmisw.orr.ont.app.OntController$$anonfun$7.apply(OntController.scala:99)\n\tat org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$liftAction(ScalatraBase.scala:270)\n\tat org.scalatra.ScalatraBase$$anonfun$invoke$1.apply(ScalatraBase.scala:265)\n\tat org.scalatra.ScalatraBase$$anonfun$invoke$1.apply(ScalatraBase.scala:265)\n\tat org.scalatra.ApiFormats$class.withRouteMultiParams(ApiFormats.scala:178)\n\tat org.mmisw.orr.ont.app.BaseController.withRouteMultiParams(BaseController.scala:11)\n\tat org.scalatra.ScalatraBase$class.invoke(ScalatraBase.scala:264)\n\tat org.mmisw.orr.ont.app.BaseController.org$scalatra$json$JsonSupport$$super$invoke(BaseController.scala:11)\n\tat org.scalatra.json.JsonSupport$$anonfun$invoke$1.apply(JsonSupport.scala:74)\n\tat org.scalatra.json.JsonSupport$$anonfun$invoke$1.apply(JsonSupport.scala:68)\n\tat org.scalatra.ApiFormats$class.withRouteMultiParams(ApiFormats.scala:178)\n\tat org.mmisw.orr.ont.app.BaseController.withRouteMultiParams(BaseController.scala:11)\n\tat org.scalatra.json.JsonSupport$class.invoke(JsonSupport.scala:68)\n\tat org.mmisw.orr.ont.app.BaseController.invoke(BaseController.scala:11)\n\tat org.scalatra.ScalatraBase$$anonfun$runRoutes$1$$anonfun$apply$8.apply(ScalatraBase.scala:240)\n\tat org.scalatra.ScalatraBase$$anonfun$runRoutes$1$$anonfun$apply$8.apply(ScalatraBase.scala:238)\n\tat scala.Option.flatMap(Option.scala:171)\n\tat org.scalatra.ScalatraBase$$anonfun$runRoutes$1.apply(ScalatraBase.scala:238)\n\tat org.scalatra.ScalatraBase$$anonfun$runRoutes$1.apply(ScalatraBase.scala:237)\n\tat scala.collection.immutable.Stream.flatMap(Stream.scala:493)\n\tat org.scalatra.ScalatraBase$class.runRoutes(ScalatraBase.scala:237)\n\tat org.scalatra.ScalatraServlet.runRoutes(ScalatraServlet.scala:49)\n\tat org.scalatra.ScalatraBase$class.runActions$1(ScalatraBase.scala:163)\n\tat org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply$mcV$sp(ScalatraBase.scala:175)\n\tat org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:175)\n\tat org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:175)\n\tat org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$cradleHalt(ScalatraBase.scala:193)\n\tat org.scalatra.ScalatraBase$class.executeRoutes(ScalatraBase.scala:175)\n\tat org.scalatra.ScalatraServlet.executeRoutes(ScalatraServlet.scala:49)\n\tat org.scalatra.ScalatraBase$$anonfun$handle$1.apply$mcV$sp(ScalatraBase.scala:113)\n\tat org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:113)\n\tat org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:113)\n\tat scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)\n\tat org.scalatra.DynamicScope$class.withResponse(DynamicScope.scala:80)\n\tat org.scalatra.ScalatraServlet.withResponse(ScalatraServlet.scala:49)\n\tat org.scalatra.DynamicScope$$anonfun$withRequestResponse$1.apply(DynamicScope.scala:60)\n\tat scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)\n\tat org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:71)\n\tat org.scalatra.ScalatraServlet.withRequest(ScalatraServlet.scala:49)\n\tat org.scalatra.DynamicScope$class.withRequestResponse(DynamicScope.scala:59)\n\tat org.scalatra.ScalatraServlet.withRequestResponse(ScalatraServlet.scala:49)\n\tat org.scalatra.ScalatraBase$class.handle(ScalatraBase.scala:111)\n\tat org.scalatra.ScalatraServlet.org$scalatra$servlet$ServletBase$$super$handle(ScalatraServlet.scala:49)\n\tat org.scalatra.servlet.ServletBase$class.handle(ServletBase.scala:43)\n\tat org.mmisw.orr.ont.app.BaseController.org$scalatra$CorsSupport$$super$handle(BaseController.scala:11)\n\tat org.scalatra.CorsSupport$$anonfun$handle$1.apply$mcV$sp(CORSSupport.scala:202)\n\tat org.scalatra.CorsSupport$$anonfun$handle$1.apply(CORSSupport.scala:190)\n\tat org.scalatra.CorsSupport$$anonfun$handle$1.apply(CORSSupport.scala:190)\n\tat scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)\n\tat org.scalatra.DynamicScope$class.withResponse(DynamicScope.scala:80)\n\tat org.scalatra.ScalatraServlet.withResponse(ScalatraServlet.scala:49)\n\tat org.scalatra.DynamicScope$$anonfun$withRequestResponse$1.apply(DynamicScope.scala:60)\n\tat scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)\n\tat org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:71)\n\tat org.scalatra.ScalatraServlet.withRequest(ScalatraServlet.scala:49)\n\tat org.scalatra.DynamicScope$class.withRequestResponse(DynamicScope.scala:59)\n\tat org.scalatra.ScalatraServlet.withRequestResponse(ScalatraServlet.scala:49)\n\tat org.scalatra.CorsSupport$class.handle(CORSSupport.scala:188)\n\tat org.mmisw.orr.ont.app.OntController.org$scalatra$servlet$FileUploadSupport$$super$handle(OntController.scala:24)\n\tat org.scalatra.servlet.FileUploadSupport$class.handle(FileUploadSupport.scala:93)\n\tat org.mmisw.orr.ont.app.OntController.handle(OntController.scala:24)\n\tat org.scalatra.ScalatraServlet.service(ScalatraServlet.scala:54)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:729)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)\n\tat org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)\n\tat org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)\n\tat org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)\n\tat org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:522)\n\tat org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)\n\tat org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)\n\tat org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)\n\tat org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)\n\tat org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)\n\tat org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:1110)\n\tat org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)\n\tat org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:785)\n\tat org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1425)\n\tat org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n\tat org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\n\tat java.lang.Thread.run(Thread.java:745)\n"
```

**Comment by carueda** [comment] 2017-04-12 01:37
Lewis:  Thanks for testing the ORR software (via the COR instance).

Yes, it seems that Jena is complaining about an invalid URI, but I would like to reproduce and confirm.

BTW, I just "transferred" your report to the orr-portal repo (which is one of the core repos for the ORR software) at https://github.com/mmisw/orr-portal/issues/98 (\*). Let's please continue the discussion there.

If you can provide a copy of your file, I can then try to reproduce the behavior.

(\*) I understand this ESIPfed/cor was mainly intended for the "management" for the installation/configuration of the COR instance)

**Comment by lewismc** [comment] 2017-04-12 01:45
ack, I'll see you over on [mmisw/orr-portal#98](https://github.com/mmisw/orr-portal/issues/98)

**Closed** 2017-04-12 01:48 UTC
Labels: bug, help wanted, question
